/*
 * LineDrawingFrame.java
 *
 * Created on 10 februari 2005, 15:14
 */

package sortsApp;

import cassis.form.*;
import sortsApp.*;
import java.awt.*; // For Graphics, etc.
import javax.swing.*; // For JPanel, etc.         
import java.awt.geom.*;  // For Ellipse2D, etc.



/**
 *
 * @author  cumming
 */
public class LineDrawingFrame extends javax.swing.JFrame {
    private Form data;
    private SortDrawerBuilder drawer = new SortDrawerBuilder();    
    
    
    /** Creates new form LineDrawingFrame */
    public LineDrawingFrame(Form data) {
        this.data = data;
        initComponents();
        drawAllLines();
        show();       
    }
    
    public void drawAllLines() {
        
    }
    
    public void drawOneLine() {
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        drawingPanel = new javax.swing.JPanel();

        getContentPane().setLayout(new java.awt.FlowLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Line Drawing Frame");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        drawingPanel.setPreferredSize(new java.awt.Dimension(500, 500));
        getContentPane().add(drawingPanel);

        pack();
    }//GEN-END:initComponents
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        //System.exit(0);
        this.dispose();
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        new LineDrawingFrame().show();
//    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel drawingPanel;
    // End of variables declaration//GEN-END:variables
    
}
