/*
 * SortLabelInputPanel.java
 *
 * Created on October 31, 2003, 4:00 PM
 */

package sortsApp;

import javax.swing.JFrame;

import com.touchgraph.graphlayout.*;
import javax.swing.JTextArea;
import sortsApp.*;

/**
 *
 * @author  cumming
 */
public class SortLabelInputPanel extends javax.swing.JPanel {
    protected JFrame parentFrame;
    
    /** Creates new form SortLabelInputPanel */
    public SortLabelInputPanel(JFrame parentFrame) {
        this.parentFrame = parentFrame;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        textArea = new javax.swing.JTextArea();

        textArea.setMinimumSize(new java.awt.Dimension(100, 16));
        textArea.setPreferredSize(new java.awt.Dimension(100, 16));
        add(textArea);

    }//GEN-END:initComponents
    
    /** Getter for property parentFrame.
     * @return Value of property parentFrame.
     *
     */
    public JFrame getParentFrame() {
        return parentFrame;
    }
    
    /** Setter for property parentFrame.
     * @param parentFrame New value of property parentFrame.
     *
     */
    public void setParentFrame(JFrame parentFrame) {
        this.parentFrame = parentFrame;
    }
    
    public JTextArea getTextArea() {
        return textArea;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
    
}
